# Generated by Django 4.1 on 2022-08-22 03:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('for_sale', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemRelationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_part', to='core.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_product', to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='parts',
            field=models.ManyToManyField(through='core.ItemRelationRecord', to='core.item'),
        ),
    ]
