# Generated by Django 4.1 on 2022-08-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemrelationrecord_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrelationrecord',
            name='product',
        ),
        migrations.AlterField(
            model_name='itemrelationrecord',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
    ]
