# Generated by Django 4.1 on 2022-08-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_itemrelationrecord_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrelationrecord',
            old_name='part',
            new_name='product_part',
        ),
    ]
