# Generated by Django 4.1 on 2022-08-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_part_itemrelationrecord_product_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrelationrecord',
            name='product_part',
        ),
        migrations.AddField(
            model_name='itemrelationrecord',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_part', to='core.item'),
        ),
        migrations.AddField(
            model_name='itemrelationrecord',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_product', to='core.item'),
            preserve_default=False,
        ),
    ]
